all:smartAttendComparison.cpp noattend.cpp total.cpp
	g++ smartAttendComparison.cpp -o smartAttendComparison -O3
	g++ noattend.cpp -o noattend -O3
	g++ total.cpp -o total -O3
clean:
	rm smartAttendComparison
	rm noattend
	rm total
